# Generated by Django 4.2.6 on 2023-11-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOKO_Clinics', '0003_alter_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
