# Generated by Django 4.2.6 on 2023-11-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOKO_Clinics', '0005_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='duration',
        ),
        migrations.AddField(
            model_name='bookings',
            name='type_id',
            field=models.IntegerField(default=0),
        ),
    ]
