# Generated by Django 4.2.6 on 2023-11-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YOKO_Clinics', '0006_remove_types_duration_bookings_type_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='types',
        ),
    ]
