# Generated by Django 4.2.6 on 2023-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOKO_Clinics', '0008_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeated_vacations',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
