# Generated by Django 4.2.6 on 2023-12-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOKO_Clinics', '0009_alter_repeated_vacations_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_specialty',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
