# Generated by Django 4.2.6 on 2023-12-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOKO_Clinics', '0010_user_main_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(default='Booked', max_length=100),
        ),
    ]
