# Generated by Django 4.2.6 on 2023-12-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOKO_Clinics', '0011_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='content',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
