# Generated by Django 4.2.6 on 2023-12-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YOKO_Clinics', '0013_remove_bookings_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='doctor_id',
            new_name='receiver_id',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='patient_id',
            new_name='sender_id',
        ),
    ]
